name: "flopit"
include:
  - path: compose/cloudbeaver-config.yaml
services:
  apiserver:
    build:
      dockerfile: server/dev.Dockerfile
    networks:
      - backend
    volumes:
      - ./server/src:/app/src
    environment:
      PRISMA_MARIADB_URL: mysql://root:${MARIADB_ROOT_PASSWORD}@${MARIADB_HOST:-mariadb}:3306/${MARIADB_DB}
    restart: on-failure
    links:
      - mariadb
      - minio
      - imgproxy
  nginx:
    image: nginx:1.25.3-alpine-slim
    networks:
      - backend
    links:
      - cloudbeaver
      - apiserver
      - minio
      - imgproxy
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 8080:80
  mariadb:
    image: mariadb:11.2.2
    healthcheck:
      test: [
        "CMD",
        "healthcheck.sh",
        "--su-mysql",
        "--connect",
        "--innodb_initialized"
      ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 1s
    networks:
      - backend
    restart: unless-stopped
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.3
    configs:
      - source: cloudbeaver
        target: /opt/cloudbeaver/conf/cloudbeaver.conf
      - source: cloudbeaver-datasource
        target: /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    links:
      - mariadb
    networks:
      - backend
    restart: unless-stopped
    environment:
      CB_SERVER_NAME: Base de données Flopit
      CB_SERVER_URL: ${PUBLIC_URL}/_db
      CB_ADMIN_NAME: _
      CB_ADMIN_PASSWORD: _
  minio:
    image: minio/minio:RELEASE.2024-02-04T22-36-13Z
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 1s
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    networks:
      - backend
    volumes:
      - minio:/data
    restart: unless-stopped
    environment:
      MINIO_SCANNER_SPEED: slowest
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
      MINIO_SITE_REGION: ${S3_REGION}
  createbuckets:
    image: minio/mc:RELEASE.2024-01-31T08-59-40Z
    depends_on:
      - minio
    networks:
      - backend
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      /usr/bin/mc mb minio/attachment-images;
      exit 0;"
  imgproxy:
    links:
      - minio
    image: darthsim/imgproxy:v3.21.0
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      timeout: "10s"
      interval: "1m30s"
      retries: 3
      start_period: 40s
      start_interval: 1s
    networks:
      - backend
    restart: unless-stopped
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_QUALITY: 85
      IMGPROXY_WORKERS: 8
      IMGPROXY_REQUESTS_QUEUE_SIZE: 32
      IMGPROXY_PATH_PREFIX: '/image/'
      IMGPROXY_ENABLE_DEBUG_HEADERS: true
      IMGPROXY_DEVELOPMENT_ERRORS_MODE: true
      IMGPROXY_MAX_SRC_RESOLUTION: 40 #megapixels
      IMGPROXY_MAX_SRC_FILE_SIZE: 10485760
      IMGPROXY_MAX_ANIMATION_FRAMES: 24
      IMGPROXY_ALLOW_ORIGIN: "*"
      IMGPROXY_ALLOWED_SOURCES: s3://, https://
      IMGPROXY_JPEG_PROGRESSIVE: true
      IMGPROXY_USE_S3: true
      IMGPROXY_S3_ENDPOINT: http://minio:9000/
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      IMGPROXY_S3_REGION: ${S3_REGION}
      IMGPROXY_MALLOC: tcmalloc
  db-deploy:
    build:
      dockerfile: server/db-deploy.Dockerfile
    networks:
      - backend
    environment:
      PRISMA_MARIADB_URL: mysql://root:${MARIADB_ROOT_PASSWORD}@${MARIADB_HOST:-mariadb}:3306/${MARIADB_DB}
    restart: on-failure
    links:
      - mariadb
networks:
  backend:
volumes:
  cloudbeaver:
  mariadb:
  minio:
configs:
  nginx:
    file: compose/nginx.conf
