services:
  devserver:
    build:
      dockerfile: dev.Dockerfile
    networks:
      - backend
    volumes:
      - ./server/src:/app/server/src
      - ./client/src:/app/client/src
      - ./shared:/app/shared
      - mariadb-import:/db-import
    environment:
      PRISMA_MARIADB_URL: ${PRISMA_MARIADB_URL}
      PRISMA_ROOT_MARIADB_URL: ${PRISMA_ROOT_MARIADB_URL}
      REDIS_URL: redis://redis
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
      S3_ENDPOINT: minio
      S3_PORT: 9000
      S3_SSL: false
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      IMGPROXY_URL: http://imgproxy:8080/image/
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}
      PUBLIC_URL: ${PUBLIC_URL}
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      db-deploy:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    links:
      - mariadb
      - minio
      - redis
      - imgproxy:nginx
    extra_hosts:
      - "apiserver:127.0.0.1"
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget 127.0.0.1:3000/health -O - && wget 127.0.0.1:4200 -O -" ]
      timeout: "10s"
      interval: "1m30s"
      retries: 3
      start_period: 40s
      start_interval: 1s
  nginx:
    links:
      - devserver:apiserver
      - devserver:client
      - cloudbeaver
  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.3
    configs:
      - source: cloudbeaver
        target: /opt/cloudbeaver/conf/cloudbeaver.conf
      - source: cloudbeaver-datasource
        target: /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources-template.json
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    links:
      - mariadb
    networks:
      - backend
    restart: unless-stopped
    entrypoint: [ "/bin/bash", "-c", "
      cp /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources-template.json /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json;
      sed -i 's/MARIADB_DB/${MARIADB_DB}/g' /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json;
      sed -i 's/MARIADB_ROOT_PASSWORD/${MARIADB_ROOT_PASSWORD}/g' /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json;
      /opt/cloudbeaver/run-server.sh;
    " ]
    environment:
      CB_SERVER_NAME: Base de données Flopit
      CB_SERVER_URL: ${PUBLIC_URL}/_db
      CB_ADMIN_NAME: _
      CB_ADMIN_PASSWORD: _
  seed:
    depends_on:
      devserver:
        condition: service_healthy
    links:
      - devserver:apiserver
volumes:
  cloudbeaver:
configs:
  cloudbeaver:
    file: compose/cloudbeaver/config.json5
  cloudbeaver-datasource:
    file: compose/cloudbeaver/datasources.json