name: "flopit"
include:
  - path: compose/cloudbeaver-config.yaml
services:
  nginx:
    image: nginx:1.25.3-alpine-slim
    networks:
      - backend
    links:
      - cloudbeaver
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 8080:80
  mariadb:
    image: mariadb:11.2.2
    healthcheck:
      test: [
        "CMD",
        "healthcheck.sh",
        "--su-mysql",
        "--connect",
        "--innodb_initialized"
      ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 1s
    networks:
      - backend
    restart: unless-stopped
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.3
    configs:
      - source: cloudbeaver
        target: /opt/cloudbeaver/conf/cloudbeaver.conf
      - source: cloudbeaver-datasource
        target: /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    links:
      - mariadb
    networks:
      - backend
    restart: unless-stopped
    environment:
      CB_SERVER_NAME: Base de données Flopit
      CB_SERVER_URL: ${PUBLIC_URL}/_db
      CB_ADMIN_NAME: _
      CB_ADMIN_PASSWORD: _
  db-deploy:
    build:
      dockerfile: server/db-deploy.Dockerfile
    networks:
      - backend
    environment:
      PRISMA_MARIADB_URL: mysql://root:${MARIADB_ROOT_PASSWORD}@${MARIADB_HOST:-mariadb}:3306/${MARIADB_DB}
    restart: on-failure
    links:
      - mariadb
networks:
  backend:
volumes:
  cloudbeaver:
  mariadb:
configs:
  nginx:
    file: compose/nginx.conf
