configs:
  cloudbeaver:
    content: |
      {
        server: {
          serverPort: 8978,

          workspaceLocation: "workspace",
          contentRoot: "web",
          driversLocation: "drivers",

          sslConfigurationPath:"workspace/.data/ssl-config.xml",

          rootURI: "/_db",
          serviceURI: "/api/",

          productConfiguration: "conf/product.conf",

          expireSessionAfterPeriod: 1800000,

          develMode: false,

          enableSecurityManager: false,

          sm: {
            enableBruteForceProtection: "true",
            maxFailedLogin: "10",
            minimumLoginTimeout: "1",
            blockLoginPeriod: "300",
            passwordPolicy: {
              minLength: "8",
              requireMixedCase: "true",
              minNumberCount: "1",
              minSymbolCount: "0"
            }
          },

          database: {
            driver: "h2_embedded_v2",
            url: "jdbc:h2:$${workspace}/.data/cb.h2v2.dat",
            initialDataConfiguration: "conf/initial-data.conf",
            pool: {
              minIdleConnections: 4,
              maxIdleConnections: 10,
              maxConnections: 100,
              validationQuery: "SELECT 1"
            }
          }

        },
        app: {
          anonymousAccessEnabled: true,
          anonymousUserRole: "user",
          authenticationEnabled: false,
          forwardProxy: "X-Forwarded-For",
          grantConnectionsAccessToAnonymousTeam: true,
          supportsCustomConnections: false,
          showReadOnlyConnectionInfo: false,

          publicCredentialsSaveEnabled: true,
          adminCredentialsSaveEnabled: true,

          resourceManagerEnabled: true,

          resourceQuotas: {
            dataExportFileSizeLimit: 10000000,
            resourceManagerFileSizeLimit: 500000,
            sqlMaxRunningQueries: 100,
            sqlResultSetRowsLimit: 100000,
            sqlResultSetMemoryLimit: 2000000,
            sqlTextPreviewMaxLength: 4096,
            sqlBinaryPreviewMaxLength: 261120
          },
          enabledAuthProviders: [
          ],

          disabledDrivers: [
            "local",
            "sqlite:sqlite_jdbc",
            "h2:h2_embedded",
            "h2:h2_embedded_v2",
            "clickhouse:yandex_clickhouse"
          ]

        }

      }
  cloudbeaver-datasource:
    content: |
      {
        "folders": {},
        "connections": {
          "mariaDB-18d7a4edd64-4256efdf3c48b33a": {
            "provider": "mysql",
            "driver": "mariaDB",
            "name": "mariadb",
            "save-password": true,
            "configuration": {
              "host": "mariadb",
              "port": "3306",
              "database": "${MARIADB_DB}",
              "url": "jdbc:mariadb://mariadb:3306",
              "configurationType": "MANUAL",
              "type": "dev",
              "auth-model": "native",
              "auth-properties" : {
                "user": "root",
                "password": "${MARIADB_ROOT_PASSWORD}"
              }
            }
          }
        }
      }